const config = require(`../config.js`);

module.exports = {
    footer_request: `Requested by: @`,
    lang_perm: `❌ You do not have permission \`MANAGE_MESSAGES\``,
    lang_valid: `❌ Please enter a vaild language (\`cz\`, \`en\`, \`sk\`)`,
    lang_err: `❌ This language is already set on the server`,
    prefix_error: `❌ Please type a valid prefix.`,
    set_prefix: ` The prefix on this server has been changed to `,  
    title_error: `Lion | Error`,
    unknown_command: `❌ This command does not exist`,
    addemote_specify: `❌ You must specify an emoticon URL`,
    addemote_valid_url: `❌ This does not look like the correct url`,
    addemote_spec_name: `❌ You must specify an emoticon name`,
    addemote_permission: `❌ You do not have permission \`MANAGE_MESSAGES\``,
    addemote_suc: `The emoticon`,
    addemote_ces: `was created successfully`,
    addemote_error: `❌ An error occurred while creating`,
    ban_permission: `❌ You do not have permission \`BAN_MEMBERS\``,
    ban_mention: `❌ Missing mention a valid member of this server`,
    ban_yourself: `❌ You can't ban yourself`,
    ban_cannot: `❌ The user cannot be banned`,
    ban_banned: `banned`,
    ban_reason: `Reason:`,
    ban_error: `❌ An error occurred`,
    clear_succes: `Messages deleted :ok_hand:`,
    kick_permission: `❌ You do not have permission \`KICK_MEMBERS\``,
    kick_yourself: `❌ You can't kick yourself`,
    kick_cannot: `❌ The user cannot be kicked`,
    kick_kicked: `kicked`,
    mute_perm: `❌ You do not have permission \`MANAGE_MESSAGES\``,
    mute_yourself: `❌ You can't mute yourself`,
    mute_role: `❌ This user cannot be muted, it has a higher role`,
    mute_create: `❌ Mute role is not created on this server`,
    mute_has: `❌ This user already has mute`,
    mute_set: `set`,
    slowmode_time: `❌ You must specify the time you want to set`,
    slowmode_number: `❌ This doesn't look like a number`,
    slowmode_succes: `Slowmode for this channel was successfully set to`,
    slowmode_seconds: `seconds`,
    unban_revoke: `revoked`,
    unban_from: `from`,
    unban_id: `❌ A user with this ID was not found`,
    unban_missing: `❌ Missing user ID`,
    unmute_delete: `delete`,
    unmute_no: `❌ This user don't have mute`,
    unmute_cannot: `❌ This user cannot be unmuted, it has a higher role`,
    unmute_yourself: `❌ You can't unmute yourself`,
    birb: `Lion | Random birb`,
    dog: `Lion | Random dog`,
    doge: `Lion | Random doge`,
    duck: `Lion | Random duck`,
    fox: `Lion | Random fox`,
    koala: `Lion | Random koala`,
    lizzy: `Lion | Random lizzard`,
    panda: `Lion | Random panda`,
    cat: `Lion | Random cat`,
    dev_perm: `❌ This command is only for developers`,
    economy_wallet: `Wallet`,
    bio_set: `❌ You must enter the text you want to set`,
    bio_succes: `Bio successfully set to`,
    daily_collected: `❌ Your daily reward has already been collected`,
    daily_again: `Collect it again in`,
    daily_succes: `Your daily reward was successfully collected`,
    daily_recived: `Today you get`,
    bio_no: `has no bio`,
    work_today: `❌ You've worked today`,
    work_try: `try again at`,
    work_worked: `Today you worked as`,
    work_get: `and get`,
    work_plumber: `Plumber`,
    work_builder: `Builder`,
    work_cook: `Cook`,
    work_painter: `Painter`,
    work_baker: `Baker`,
    work_electrican: `Electrican`,
    work_policeman: `Policeman`,
    work_fireman: `Fireman`,
    mention_people: `❌ Please don't mention people`,
    too_characters: `❌ Don't exceed 21 characters`,
    add_text: `❌ Please add some text`,
    miss_mention: `❌ Missing mention a valid member of this server`,
    apod_looking: `Looking to **NASA** database...`,
    apod_name: `Name of picture:`,
    random_food: `Lion | Random food`,
    gay_is: `is on`,
    gay_end: `% gay :rainbow_flag:`,
    hot_mid: `you are on`,
    grill_mid: `GRILLED`,
    grill_yourself: `Why would you want to grill yourself...`,
    hug_alone: `You are alone? come to me...`,
    hug_mid: `hug`,
    kill_yourself: `Why would you want to kill yourself...`,
    kill_mid: `killed`,
    people_space: `In space right now is`,
    people: `peoples`,
    people_one: `There is currently **1** person in space`,
    people_zero: `There is no one in space at the moment`,
    pika_title: `Lion | Random pikachu`,
    like_text: `❌ This doesn't look like text`,
    qr_succes: `Your QR code`,
    yn_ask: `❌ A question must be asked`,
    yn_error: `❌  This doesn't seem like a question [Must be **?** at the end]`,
    yn_ansfer: `My ansver:`,
    yn_question: `Your question:`,
    giveaway_perm: `❌ You do not have permission \`MANAGE_MESSAGES\``,
    giveaway_marked: `❌ You have to mark the channel where the giveaway was be`,
    giveaway_leng: `❌ You must enter a giveaway length`,
    giveaway_winner: `❌ You must enter the number of winners`,
    giveaway_prize: `❌ You must enter a prize`,
    giveaway_succes: `Giveaway created in `,
    giveaway_new: `New winner/s`,
    giveaway_ended: `GIVEAWAY ENDED`,
    giveaway_time: `Remaining time`,
    giveaway_join: `Click on 🎉 to join`,
    giveaway_you: `you won`,
    giveaway_congr: `Congratulations`,
    giveaway_cancel: `Giveaway canceled`,
    giveaway_winners: `Winner/s`,
    giveaway_end: `Ended`,
    giveaway_seconds: `seconds`,
    giveaway_minutes: `minutes`,
    giveaway_hours: `hours`,
    giveaway_days: `days`,
    giveaway_id: `❌ You must enter a giveaway ID`,
    giveaway_not: `❌ Giveaway with given ID not found`,
    giveaway_close: `Giveaway will be closed by`,
    giveaway_is: `This giveaway is canceled`,
    giveaway_not_yet: `❌ Giveaway with the given ID has not been ended yet`,
    giveaway_new_winners: `:tada: New winner/s : {winners}`,
    changelog: `❌ The changelog is only available on the support server, if you are not yet on the support server, click [here](https://discord.gg/ED7BfHf)`,
    suggestion: `✅ Your idea has been successfully submitted to the support server`,
    invite: `**Lion** - [Click here](https://discord.com/oauth2/authorize?client_id=617029072006021140&scope=bot&permissions=2146958847)`,
    support: `If you have any problem click [here](https://discord.gg/ED7BfHf)`,
    vote: `If you want to vote for Lion click [here](https://top.gg/bot/617029072006021140/vote) thank you very much for every vote`,
    music_channel: `❌ You must be in a voice channel`,
    music_url: `❌ You must enter a URL or song title`,
    music_play: `Now playing`,
    server_name: `Server name`,
    server_id: `Server ID`,
    server_owner: `Server owner`,
    server_created: `Server created`,
    server_boosts: `Boosts`,
    server_users: `Users`,
    server_channels: `Channels`,
    server_verification: `Verification`,
    avatar_from: `Avatar from`,
    bot_uptime: `Bot's uptime`,
    server_uptime: `Server uptime`,
    calc_example: `❌ You must enter the example you want to calculate`,
    calc_error: `❌ Unknown numbers`,
    calc_start: `You wanted to calculate`,
    calc_result: `Result`,
    yes: `Yes`,
    no: `No`,
    no_game: `no game playing`,
    username: `Username`,
    status: `Status`,
    game: `Game`,
    bot: `Bot`,
    acc_cre: `Account created`,
    server_join: `Joined to server`,
    weather_town: `❌ Please enter a city or village name`,
    wather_notown: `❌ The town or village does not exist`,
    weather_in: `Weather in`,
    weather_temp: `Temperature`,
    weather_feels: `Feels like`,
    weather_wet: `Wet`,
    bot_name: `Name`,
    bot_server: `Servers`,
    bot_users: `Users`,
    memes_mention: `❌ Missing mention a valid member of this server`,
    memes_text: `❌ Add some text`,
    memes_nomention: `❌ Don't mention a member of this server`,
    memes_34: `❌ The text cannot be longer than 34 letters`,
    memes_error: `❌ An error occurred`,
    memes_100: `❌ The text cannot be longer than 100 letters`,
    memes_27: `❌ The text cannot be longer than 27 letters`,
    memes_yourself: `❌ You can't mention yourself`,
    random_meme: `Lion | Random meme`,
    missing_mention: `❌ Missing mention a valid member of this server`,
    help_title: `Lion | Commands`,
    help_footer: `For a specific command, enter +help <command>`,
    prefix_emoji: `❌ In prefix can't be a emoji`,
    prefix_2: `❌ The prefix cannot be longer than 2 letters`,
    link_redirect: `Redirected`,
    link_created: `Created`,
    link_footer: `URL shortener from`,
    link_url: `❌ URL is not defined`,
    link_invalid: `❌ URL format is invalid`,
    link_taken: `❌ The alias you entered is already taken, maybe try another one`,
    link_succes: `Done, your Link is`,
    minecraft_nick: `❌ You must specify a player name`,
    minecraft_ip: `❌ You must specify a server IP`,
    minecraft_head: `Head from`,
    minecraft_version: `Version`,
    minecraft_players: `Players`,
    minecraft_skin: `Skin from`,
    music_channel: `❌ You must be in a voice channel`,
    music_nothing: `❌ There is nothing playing`,
    music_now: `Now Playing`,
    music_enter: `❌ Please enter a music`,
    music_provider: `❌ This song provider is not supported...`,
    music_progress: `Progression`,
    music_added_queue: `songs added to the queue`,
    music_added: `added to the queue`,
    music_currently: `Currently playing`,
    music_end: `There is no more music in the queue`,
    music_member: `Stop playing, there is no more member in the voice channel`,
    music_volume: `Please enter a valid number`,
    music_volume_set: `Volume set to`,
    music_stop: `Music stopped`,
    music_song: `Song`,
    music_skipped: `skipped`,
    music_no_songs: `No songs currently playing`,
    music_resumed: `resumed`,
    music_paused: `paused`,
    music_clear: `Queue cleared`,
    server_roles: `Roles`,
    server_emojis: `Emojis`,
    freeze_succes: `This room have been temporarily closed`,
    unfreeze_succes: `This channel has been reopened`,
}